# Input and output file paths
"""
input_file_path = "en-de/testsets/newstest2014-origlang-en.en"
output_file_path = "en-de/testsets/newstest2014-origlang-en.prompt.eurollmchat.en"

input_file_path = "en-de/testsets/newstest2022-src.en"
output_file_path = "en-de/testsets/newstest2022-src.prompt.en"
input_file_path = "en-de/testsets/newstest2023-src.en"
output_file_path = "en-de/testsets/newstest2023-src.prompt.eurollmchat.en"

input_file_path = "en-de/testsets/wmt2024-src.en"
output_file_path = "en-de/testsets/wmt2024-src.prompt.3shot.en"
input_file_path = "en-de/testsets/wmt2024-src.en"
output_file_path = "en-de/testsets/wmt2024-src.prompt.mistral-3shot.en"

input_file_path = "en-de/testsets/wmttest2024.literary.src.en-de.en.en"
output_file_path = "en-de/testsets/wmt2024-literary-src.prompt.eurollmchat.en"

input_file_path = "/home/vincent/Downloads/wmttest2024.src.en-xx.txt"
output_file_path = "en-de/testsets/wmttest2024.src.en-xx.llamachat.3shot.en"
input_file_path = "/mnt/InternalCrucial4/LLM_work/dialogsum-long.en"
output_file_path = "/mnt/InternalCrucial4/LLM_work/dialogsum-long.MLchat.en"
input_file_path = "/mnt/InternalCrucial4/LLM_work/prosocial-dialog-short.en"
output_file_path = "/mnt/InternalCrucial4/LLM_work/prosocial-dialog-short.MLchat.en"
input_file_path = "/mnt/InternalCrucial4/LLM_work/fineweb-literature-400k.en"
output_file_path = "/mnt/InternalCrucial4/LLM_work/fineweb-literature-400k.MLchat.en"
"""

input_file_path = "/mnt/InternalCrucial4/data/wmt/WMT24_GeneralMT/wmttest2024.src.en-de.en"
#output_file_path = "/mnt/InternalCrucial4/data/wmt/WMT24_GeneralMT/wmttest2024.src.en-de.eurollmchat.en"
output_file_path = "/mnt/InternalCrucial4/data/wmt/WMT24_GeneralMT/wmttest2024.src.en-de.3shotllamachat.en"

# Open the input file for reading and the output file for writing
with open(input_file_path, "r") as input_file, open(
    output_file_path, "w"
) as output_file:
    # Loop through each line in the input file
    for line in input_file:
        # Set up the prompt provided by Tower-instruct with the current line's content
        # PLEASE note the space between "<|im_start|> user" and "<|im_start|> assistant"
        # This is due to a specific behavior of onmt_tokenize
        # HF tokenizer has a similar strange behavior
        # https://github.com/huggingface/transformers/issues/31513#issuecomment-2340151976
        
        # eruollm chat
        """
        prompt = f"<|im_start|>system｟newline｠<|im_end|>｟newline｠<|im_start|>user｟newline｠Translate the following text from English into German.｟newline｠English: {line.strip()}｟newline｠German: <|im_end|>｟newline｠<|im_start|>assistant｟newline｠"  # noqa: E501
        
        prompt = f"<|im_start|>system｟newline｠<|im_end|>｟newline｠<|im_start|>user｟newline｠Translate the following text from English into Spanish.｟newline｠English: {line.strip()}｟newline｠Spanish: <|im_end|>｟newline｠<|im_start|>assistant｟newline｠"  # noqa: E501
        prompt = f"<|im_start|>system｟newline｠<|im_end|>｟newline｠<|im_start|>user｟newline｠Translate the following text from English into Czech.｟newline｠English: {line.strip()}｟newline｠Czech: <|im_end|>｟newline｠<|im_start|>assistant｟newline｠"  # noqa: E501
        prompt = f"<|im_start|>system｟newline｠<|im_end|>｟newline｠<|im_start|>user｟newline｠Translate the following text from English into Hindi.｟newline｠English: {line.strip()}｟newline｠Hindi: <|im_end|>｟newline｠<|im_start|>assistant｟newline｠"  # noqa: E501
        prompt = f"<|im_start|>system｟newline｠<|im_end|>｟newline｠<|im_start|>user｟newline｠Translate the following text from English into Icelandic.｟newline｠English: {line.strip()}｟newline｠Icelandic: <|im_end|>｟newline｠<|im_start|>assistant｟newline｠"  # noqa: E501
        prompt = f"<|im_start|>system｟newline｠<|im_end|>｟newline｠<|im_start|>user｟newline｠Translate the following text from English into Japanese.｟newline｠English: {line.strip()}｟newline｠Japanese: <|im_end|>｟newline｠<|im_start|>assistant｟newline｠"  # noqa: E501
        prompt = f"<|im_start|>system｟newline｠<|im_end|>｟newline｠<|im_start|>user｟newline｠Translate the following text from English into Russian.｟newline｠English: {line.strip()}｟newline｠Russian: <|im_end|>｟newline｠<|im_start|>assistant｟newline｠"  # noqa: E501
        prompt = f"<|im_start|>system｟newline｠<|im_end|>｟newline｠<|im_start|>user｟newline｠Translate the following text from English into Ukrainian.｟newline｠English: {line.strip()}｟newline｠Ukrainian: <|im_end|>｟newline｠<|im_start|>assistant｟newline｠"  # noqa: E501
        prompt = f"<|im_start|>system｟newline｠<|im_end|>｟newline｠<|im_start|>user｟newline｠Translate the following text from English into Chinese.｟newline｠English: {line.strip()}｟newline｠Chinese: <|im_end|>｟newline｠<|im_start|>assistant｟newline｠"  # noqa: E501
        prompt = f"<|im_start|>system｟newline｠<|im_end|>｟newline｠<|im_start|>user｟newline｠Translate the following text from Czech into Ukrainian.｟newline｠Czech: {line.strip()}｟newline｠Ukrainian: <|im_end|>｟newline｠<|im_start|>assistant｟newline｠"  # noqa: E501
        prompt = f"<|im_start|>system｟newline｠<|im_end|>｟newline｠<|im_start|>user｟newline｠Translate the following text from Japanese into Chinese.｟newline｠Japanese: {line.strip()}｟newline｠Chinese: <|im_end|>｟newline｠<|im_start|>assistant｟newline｠"  # noqa: E501
        prompt = f"<|im_start|>system｟newline｠<|im_end|>｟newline｠<|im_start|>user｟newline｠Translate the following text from English into French.｟newline｠English: {line.strip()}｟newline｠French: <|im_end|>｟newline｠<|im_start|>assistant｟newline｠"  # noqa: E501
        """
        #prompt = f"<|im_start|>user｟newline｠Translate the following text from English into German.｟newline｠English: {line.strip()}｟newline｠German: <|im_end|>｟newline｠<|im_start|>assistant｟newline｠"  # noqa: E501
        #prompt = f"<|im_start|>user｟newline｠Translate the following text from English into German.｟newline｠English: White nationalists, gun fetishists, pro-dictator right wing.. there's the danger. Deport the white supremacists.｟newline｠German: <|im_end|>｟newline｠<|im_start|>assistant｟newline｠Weiße Nationalisten, Waffenfetischisten, Diktator-Freundliche vom rechten Flügel … da liegt die Gefahr. Deportiert die weißen Rassisten.<|im_end|><|im_start|>user｟newline｠Translate the following text from English into German.｟newline｠English: It's 2023 and I still see people with iPhones actively avoid using Apple Maps.｟newline｠German: <|im_end|>｟newline｠<|im_start|>assistant｟newline｠Es ist 2023 und ich sehe immer noch Menschen mit iPhones, die aktiv die Verwendung von Apple Maps vermeiden.<|im_end|><|im_start|>user｟newline｠Translate the following text from English into German.｟newline｠English: #CNN needs to just close down. Yesterday's fiasco with #MangoMoron was an outrageous fiasco. Who at that pathetic, dying network was responsible for vetting the so-called \"independent voters\" in the audience? Which cable news \"executive\" made the call to give the fat, lying criminal this much air-time?｟newline｠German: <|im_end|>｟newline｠<|im_start|>assistant｟newline｠#CNN muss einfach den Laden dichtmachen. Das Fiasko von gestern mit #MangoMoron war einfach ungeheuerlich. Wer war bei diesem jämmerlichen, im Sterben liegenden Sender eigentlich für die Überprüfung der sogenannten „unabhängigen Wähler“ im Publikum verantwortlich? Welcher Kabelnachrichten-„Verantwortliche“ hat denn die Entscheidung getroffen, dem fetten, lügenden Kriminellen so viel Sendezeit zu geben?<|im_end|><|im_start|>user｟newline｠Translate the following text from English into German.｟newline｠English: {line.strip()}｟newline｠German: <|im_end|>｟newline｠<|im_start|>assistant｟newline｠"  # noqa: E501
        #prompt = f"<|start_header_id|>system<|end_header_id|>You are a helpful translator<<|eot_id|>|start_header_id|>user<|end_header_id|>｟newline｠Translate the following text from English into German.｟newline｠English: {line.strip()}｟newline｠German: <|eot_id|><|start_header_id|>assistant<|end_header_id|>｟newline｠"  # noqa: E501
        #prompt = f"<|start_header_id|>system<|end_header_id|>You are a helpful translator<|eot_id|><|start_header_id|>user<|end_header_id|>｟newline｠Translate the following text from English into German.｟newline｠English: {line.strip()}｟newline｠German: <|eot_id|><|start_header_id|>assistant<|end_header_id|>｟newline｠"  # noqa: E501
        
        #llamachat 0 shot
        #prompt = f"<|start_header_id|>system<|end_header_id|>You are a helpful translator<|eot_id|><|start_header_id|>user<|end_header_id|>｟newline｠Translate the following text from English into German.｟newline｠English: {line.strip()}｟newline｠German: <|eot_id|><|start_header_id|>assistant<|end_header_id|>｟newline｠"  # noqa: E501
        #prompt = f"<|start_header_id|>user<|end_header_id|>｟newline｠Translate the following text from English into German.｟newline｠English: {line.strip()}｟newline｠German: <|eot_id|><|start_header_id|>assistant<|end_header_id|>｟newline｠"  # noqa: E501

        #llamachat 3 shot
        #prompt = f"<|start_header_id|>system<|end_header_id|><|eot_id|><|start_header_id|>user<|end_header_id|>｟newline｠Translate the following text from English into German.｟newline｠English: White nationalists, gun fetishists, pro-dictator right wing.. there's the danger. Deport the white supremacists.｟newline｠German: <|eot_id|><|start_header_id|>assistant<|end_header_id|>｟newline｠Weiße Nationalisten, Waffenfetischisten, Diktator-Freundliche vom rechten Flügel … da liegt die Gefahr. Deportiert die weißen Rassisten.<|eot_id|><|start_header_id|>user<|end_header_id|>｟newline｠Translate the following text from English into German.｟newline｠English: It's 2023 and I still see people with iPhones actively avoid using Apple Maps.｟newline｠German: <|eot_id|><|start_header_id|>assistant<|end_header_id|>｟newline｠Es ist 2023 und ich sehe immer noch Menschen mit iPhones, die aktiv die Verwendung von Apple Maps vermeiden.<|eot_id|><|start_header_id|>user<|end_header_id|>｟newline｠Translate the following text from English into German.｟newline｠English: #CNN needs to just close down. Yesterday's fiasco with #MangoMoron was an outrageous fiasco. Who at that pathetic, dying network was responsible for vetting the so-called \"independent voters\" in the audience? Which cable news \"executive\" made the call to give the fat, lying criminal this much air-time?｟newline｠German: <|eot_id|><|start_header_id|>assistant<|end_header_id|>｟newline｠#CNN muss einfach den Laden dichtmachen. Das Fiasko von gestern mit #MangoMoron war einfach ungeheuerlich. Wer war bei diesem jämmerlichen, im Sterben liegenden Sender eigentlich für die Überprüfung der sogenannten „unabhängigen Wähler“ im Publikum verantwortlich? Welcher Kabelnachrichten-„Verantwortliche“ hat denn die Entscheidung getroffen, dem fetten, lügenden Kriminellen so viel Sendezeit zu geben?<|eot_id|><|start_header_id|>user<|end_header_id|>｟newline｠Translate the following text from English into German.｟newline｠English: {line.strip()}｟newline｠German: <|eot_id|><|start_header_id|>assistant<|end_header_id|>｟newline｠"  # noqa: E501
        prompt = f"<|start_header_id|>user<|end_header_id|>｟newline｠Translate the following text from English into German.｟newline｠English: White nationalists, gun fetishists, pro-dictator right wing.. there's the danger. Deport the white supremacists.｟newline｠German: <|eot_id|><|start_header_id|>assistant<|end_header_id|>｟newline｠Weiße Nationalisten, Waffenfetischisten, Diktator-Freundliche vom rechten Flügel … da liegt die Gefahr. Deportiert die weißen Rassisten.<|eot_id|><|start_header_id|>user<|end_header_id|>｟newline｠Translate the following text from English into German.｟newline｠English: It's 2023 and I still see people with iPhones actively avoid using Apple Maps.｟newline｠German: <|eot_id|><|start_header_id|>assistant<|end_header_id|>｟newline｠Es ist 2023 und ich sehe immer noch Menschen mit iPhones, die aktiv die Verwendung von Apple Maps vermeiden.<|eot_id|><|start_header_id|>user<|end_header_id|>｟newline｠Translate the following text from English into German.｟newline｠English: #CNN needs to just close down. Yesterday's fiasco with #MangoMoron was an outrageous fiasco. Who at that pathetic, dying network was responsible for vetting the so-called \"independent voters\" in the audience? Which cable news \"executive\" made the call to give the fat, lying criminal this much air-time?｟newline｠German: <|eot_id|><|start_header_id|>assistant<|end_header_id|>｟newline｠#CNN muss einfach den Laden dichtmachen. Das Fiasko von gestern mit #MangoMoron war einfach ungeheuerlich. Wer war bei diesem jämmerlichen, im Sterben liegenden Sender eigentlich für die Überprüfung der sogenannten „unabhängigen Wähler“ im Publikum verantwortlich? Welcher Kabelnachrichten-„Verantwortliche“ hat denn die Entscheidung getroffen, dem fetten, lügenden Kriminellen so viel Sendezeit zu geben?<|eot_id|><|start_header_id|>user<|end_header_id|>｟newline｠Translate the following text from English into German.｟newline｠English: {line.strip()}｟newline｠German: <|eot_id|><|start_header_id|>assistant<|end_header_id|>｟newline｠"  # noqa: E501
        
        #llama 3 shot
        #prompt = f"English: White nationalists, gun fetishists, pro-dictator right wing.. there's the danger. Deport the white supremacists.｟newline｠German: Weiße Nationalisten, Waffenfetischisten, Diktator-Freundliche vom rechten Flügel … da liegt die Gefahr. Deportiert die weißen Rassisten.<|end_of_text|>｟newline｠English: It's 2023 and I still see people with iPhones actively avoid using Apple Maps.｟newline｠German: Es ist 2023 und ich sehe immer noch Menschen mit iPhones, die aktiv die Verwendung von Apple Maps vermeiden.<|end_of_text|>｟newline｠English: #CNN needs to just close down. Yesterday's fiasco with #MangoMoron was an outrageous fiasco. Who at that pathetic, dying network was responsible for vetting the so-called \"independent voters\" in the audience? Which cable news \"executive\" made the call to give the fat, lying criminal this much air-time?｟newline｠German: #CNN muss einfach den Laden dichtmachen. Das Fiasko von gestern mit #MangoMoron war einfach ungeheuerlich. Wer war bei diesem jämmerlichen, im Sterben liegenden Sender eigentlich für die Überprüfung der sogenannten „unabhängigen Wähler“ im Publikum verantwortlich? Welcher Kabelnachrichten-„Verantwortliche“ hat denn die Entscheidung getroffen, dem fetten, lügenden Kriminellen so viel Sendezeit zu geben?<|end_of_text|>｟newline｠English: {line.strip()}｟newline｠German: "  # noqa: E501
        
        #Mistral instruct 0 shot
        #prompt = f"[INST]Translate the following text from English into German.｟newline｠English: {line.strip()}｟newline｠German: [/INST]"  # noqa: E501

        #Mistral instruct 3 shots
        #prompt = f"[INST]Translate the following text from English into German.｟newline｠English: White nationalists, gun fetishists, pro-dictator right wing.. there's the danger. Deport the white supremacists.｟newline｠German: [/INST]Weiße Nationalisten, Waffenfetischisten, Diktator-Freundliche vom rechten Flügel … da liegt die Gefahr. Deportiert die weißen Rassisten.</s>[INST]Translate the following text from English into German.｟newline｠English: It's 2023 and I still see people with iPhones actively avoid using Apple Maps.｟newline｠German: [/INST]Es ist 2023 und ich sehe immer noch Menschen mit iPhones, die aktiv die Verwendung von Apple Maps vermeiden.</s>[INST]Translate the following text from English into German.｟newline｠English: #CNN needs to just close down. Yesterday's fiasco with #MangoMoron was an outrageous fiasco. Who at that pathetic, dying network was responsible for vetting the so-called \"independent voters\" in the audience? Which cable news \"executive\" made the call to give the fat, lying criminal this much air-time?｟newline｠German: [/INST]#CNN muss einfach den Laden dichtmachen. Das Fiasko von gestern mit #MangoMoron war einfach ungeheuerlich. Wer war bei diesem jämmerlichen, im Sterben liegenden Sender eigentlich für die Überprüfung der sogenannten „unabhängigen Wähler“ im Publikum verantwortlich? Welcher Kabelnachrichten-„Verantwortliche“ hat denn die Entscheidung getroffen, dem fetten, lügenden Kriminellen so viel Sendezeit zu geben?</s>[INST]Translate the following text from English into German.｟newline｠English: {line.strip()}｟newline｠German: [/INST]"  # noqa: E501

        #Mistral 3 shots variant
        #prompt = f"[INST]Translate the following text from English into German. Give only one translation and no explanation.｟newline｠English: White nationalists, gun fetishists, pro-dictator right wing.. there's the danger. Deport the white supremacists.｟newline｠German: [/INST]Weiße Nationalisten, Waffenfetischisten, Diktator-Freundliche vom rechten Flügel … da liegt die Gefahr. Deportiert die weißen Rassisten.</s>[INST]Translate the following text from English into German. Give only one translation and no explanation.｟newline｠English: It's 2023 and I still see people with iPhones actively avoid using Apple Maps.｟newline｠German: [/INST]Es ist 2023 und ich sehe immer noch Menschen mit iPhones, die aktiv die Verwendung von Apple Maps vermeiden.</s>[INST]Translate the following text from English into German. Give only one translation and no explanation.｟newline｠English: #CNN needs to just close down. Yesterday's fiasco with #MangoMoron was an outrageous fiasco. Who at that pathetic, dying network was responsible for vetting the so-called \"independent voters\" in the audience? Which cable news \"executive\" made the call to give the fat, lying criminal this much air-time?｟newline｠German: [/INST]#CNN muss einfach den Laden dichtmachen. Das Fiasko von gestern mit #MangoMoron war einfach ungeheuerlich. Wer war bei diesem jämmerlichen, im Sterben liegenden Sender eigentlich für die Überprüfung der sogenannten „unabhängigen Wähler“ im Publikum verantwortlich? Welcher Kabelnachrichten-„Verantwortliche“ hat denn die Entscheidung getroffen, dem fetten, lügenden Kriminellen so viel Sendezeit zu geben?</s>[INST]Translate the following text from English into German. Give only one translation and no explanation.｟newline｠English: {line.strip()}｟newline｠German: [/INST]"  # noqa: E501
        output_file.write(prompt + "\n")
